create table Circuit (circuitId int(10) not null auto_increment, circuitRef varchar(255), name varchar(255), location varchar(255), country varchar(255), primary key (circuitId));
create table Constructor (constructorId int(10) not null auto_increment, constructorRef varchar(255), name varchar(255), nationality varchar(255), primary key (constructorId));
create table Race (raceId int(10) not null auto_increment, year varchar(255), circuitId int(10) not null, name varchar(255), primary key (raceId));
create table Driver (driverId int(10) not null auto_increment, driverRef varchar(255), forename varchar(255), surname varchar(255), dob varchar(255), nationality varchar(255), primary key (driverId));
create table Status (statusId int(10) not null auto_increment, status varchar(255), primary key (statusId));
create table ConstructorStandings (constructorStandingsId int(10) not null, raceId int(10) not null, constructorId int(10) not null, points float, position int(10), primary key (constructorStandingsId, raceId, constructorId));
create table DriverStandings (driverStandingsId int(10) not null, raceId int(10) not null, driverId int(10) not null, points float, position int(10), primary key (driverStandingsId, raceId, driverId));
create table LapTime (raceId int(10) not null, driverId int(10) not null, lap int(10) not null, position int(10), time varchar(255), primary key (raceId, driverId, lap));
create table PitStop (raceId int(10) not null, driverId int(10) not null, stop int(10) not null, lap int(10), duration varchar(255), primary key (raceId, driverId, stop));
create table Result (resultId int(10) not null auto_increment, raceId int(10) not null, driverId int(10) not null, constructorId int(10) not null, grid int(10), position float, points float, statusId int(10) not null, primary key (resultId));
alter table Race add constraint FKRace995690 foreign key (circuitId) references Circuit (circuitId);
alter table ConstructorStandings add constraint FKConstructo446736 foreign key (raceId) references Race (raceId);
alter table ConstructorStandings add constraint FKConstructo592625 foreign key (constructorId) references Constructor (constructorId);
alter table DriverStandings add constraint FKDriverStan361321 foreign key (raceId) references Race (raceId);
alter table DriverStandings add constraint FKDriverStan110217 foreign key (driverId) references Driver (driverId);
alter table LapTime add constraint FKLapTime316840 foreign key (driverId) references Driver (driverId);
alter table LapTime add constraint FKLapTime816787 foreign key (raceId) references Race (raceId);
alter table PitStop add constraint FKPitStop409811 foreign key (driverId) references Driver (driverId);
alter table PitStop add constraint FKPitStop61727 foreign key (raceId) references Race (raceId);
alter table Result add constraint FKResult720063 foreign key (raceId) references Race (raceId);
alter table Result add constraint FKResult779988 foreign key (driverId) references Driver (driverId);
alter table Result add constraint FKResult212165 foreign key (constructorId) references Constructor (constructorId);
alter table Result add constraint FKResult790804 foreign key (statusId) references Status (statusId);
